/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Gui;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;


import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.text.SimpleDateFormat;

import org.apache.commons.io.FileUtils;
import java.util.Date;
/**
 *
 * @author ACER
 */
public class mn_audit extends javax.swing.JFrame {

    /** Creates new form mn_audit */

    File file;
    JFileChooser jfc;
    public mn_audit() {
        initComponents();
        display_data();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        ktp = new javax.swing.JTextField();
        slip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lihat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        periode = new javax.swing.JTextField();
        penghasilan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ubah = new javax.swing.JButton();
        npwp = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        rumah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        sp = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pinjaman = new javax.swing.JTextField();
        angsuran = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tgl = new com.toedter.calendar.JDateChooser();

        setTitle("Menu Audit");

        jLabel7.setText("No. Telp");

        no_telp.setEditable(false);

        ktp.setEditable(false);

        slip.setEditable(false);

        jLabel8.setText("ID");

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setText("Periode");

        jLabel5.setText("KTP");

        jLabel6.setText("Slip Gajih");

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Menu Audit");

        jLabel2.setText("Nama");

        periode.setEditable(false);

        penghasilan.setEditable(false);

        jLabel4.setText("NIK ");

        jLabel11.setText("NPWP");

        nama.setEditable(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel14.setText("Surat Pernyataan");

        nik.setEditable(false);

        jLabel15.setText("Pencairan");

        ubah.setText("Perbarui");
        ubah.setMaximumSize(new java.awt.Dimension(94, 29));
        ubah.setMinimumSize(new java.awt.Dimension(94, 29));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        npwp.setEditable(false);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        rumah.setEditable(false);

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "NIK", "No. Telp", "Penghasilan", "Pinjaman", "Periode", "KTP", "Slip Gajih", "NPWPl"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        sp.setEditable(false);

        jLabel12.setText("Rumah");

        jLabel9.setText("Penghasilan");

        jLabel10.setText("Pinjaman");

        pinjaman.setEditable(false);
        pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamanActionPerformed(evt);
            }
        });

        angsuran.setEditable(false);
        angsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angsuranActionPerformed(evt);
            }
        });

        jLabel13.setText("Angsuran");

        jButton1.setText("Tolak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rumah)
                                    .addComponent(sp)
                                    .addComponent(npwp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ktp)
                                            .addComponent(slip, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periode)
                                    .addComponent(no_telp)
                                    .addComponent(nik)
                                    .addComponent(nama)
                                    .addComponent(id)
                                    .addComponent(pinjaman)
                                    .addComponent(penghasilan)
                                    .addComponent(angsuran))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(712, 712, 712)
                        .addComponent(lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reset)
                    .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihat)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            new SaveImage(ID).setVisible(true);
        }

    }//GEN-LAST:event_lihatActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String PENCAIRAN = String.valueOf(fm.format(tgl.getDate()));
        if(PENCAIRAN.equals("")){
            JOptionPane.showMessageDialog(null,"Harap isi formulir dengan benar dan lengkap !");
        }else if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah !");
        }else{
            try {
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE tb_pengajuan SET tanggal_pencairan = '"+PENCAIRAN+"' WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berkas berhasil dilengkapi");
                display_data(); //refresh table
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Berkas gagal dilengkapi");
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String ID = jTable1.getValueAt(baris, 0).toString();
        id.setText(ID);
        String NAMA = jTable1.getValueAt(baris, 1).toString();
        nama.setText(NAMA);
        String NIK = jTable1.getValueAt(baris, 2).toString();
        nik.setText(NIK);
        String NO_TELP = jTable1.getValueAt(baris, 3).toString();
        no_telp.setText(NO_TELP);
        String PENGHASILAN = jTable1.getValueAt(baris, 4).toString();
        penghasilan.setText(PENGHASILAN);
        String PINJAMAN = jTable1.getValueAt(baris, 5).toString();
        pinjaman.setText(PINJAMAN);
        String PERIODE = jTable1.getValueAt(baris, 6).toString();
        periode.setText(PERIODE);
        String ANGSURAN = jTable1.getValueAt(baris, 7).toString();
        angsuran.setText(ANGSURAN);
        String KTP = jTable1.getValueAt(baris, 8).toString();
        ktp.setText(KTP);
        String SLIP = jTable1.getValueAt(baris, 9).toString();
        slip.setText(SLIP);
        String NPWP = jTable1.getValueAt(baris, 10).toString();
        npwp.setText(NPWP);
        String RUMAH = jTable1.getValueAt(baris, 11).toString();
        rumah.setText(RUMAH);
        String SP = jTable1.getValueAt(baris, 12).toString();
        sp.setText(SP);
        String TGL = jTable1.getValueAt(baris, 13).toString();
//        String sDate1="31/12/1998";
        try {
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(TGL);
            tgl.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(mn_audit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinjamanActionPerformed

    private void angsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angsuranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            try{
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement(" DELETE FROM tb_pengajuan WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nasabah Ditolak");
                display_data();
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Nasabah gagal ditoak");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reset (){
        id.setText("");
        nama.setText("");
        nik.setText("");
        no_telp.setText("");
        penghasilan.setText("");
        periode.setText("");
        pinjaman.setText("");
        angsuran.setText("");
        ktp.setText("");
        slip.setText("");
        npwp.setText("");
        rumah.setText("");
        sp.setText("");
        Date date = new Date();
        tgl.setDate(date);
//        tgl.setDateFormatString(dan);
//        pencairan.setText("");
    }
    
     
    private void display_data()
    {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("NIK");
        tabel.addColumn("No. Telp");
        tabel.addColumn("Penghasilan");
        tabel.addColumn("Pinjaman");
        tabel.addColumn("Periode");
        tabel.addColumn("Angsuran");
        tabel.addColumn("KTP");
        tabel.addColumn("Slip Gajih");
        tabel.addColumn("NPWP");
        tabel.addColumn("Rumah");
        tabel.addColumn("SP");
        tabel.addColumn("Pencairan");
        String STATUS = "Audit";
        
        try{
            java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
            java.sql.Statement s = Vconn.createStatement();
            java.sql.ResultSet r = s.executeQuery("SELECT * FROM tb_pengajuan WHERE status = '"+STATUS+"' ");
//            SELECT id_user FROM tb_user ORDER BY id_user DESC LIMIT 1
            
            //menampilkan data
            while (r.next()){
                tabel.addRow(new Object[]{
                   r.getString(1),r.getString(2),r.getString(3), r.getString(4), r.getString(5),r.getString(6),r.getString(7), r.getString(8),r.getString(9),r.getString(10),r.getString(11), r.getString(13),r.getString(14),r.getString(15)
                }); 
            }
            jTable1.setModel(tabel);
            
            
        }catch (SQLException e){
            
        }
    }

//    private void tanggal(){
//        Date ys= new Date();
//        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
//        tgl.setDateFormatString(s.format(ys));
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angsuran;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ktp;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField npwp;
    private javax.swing.JTextField penghasilan;
    private javax.swing.JTextField periode;
    private javax.swing.JTextField pinjaman;
    private javax.swing.JButton reset;
    private javax.swing.JTextField rumah;
    private javax.swing.JTextField slip;
    private javax.swing.JTextField sp;
    private com.toedter.calendar.JDateChooser tgl;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

}
