/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import org.apache.commons.io.FileUtils;

/**
 *
 * @author ACER
 */
public class mn_pengajuan extends javax.swing.JFrame {

    /**
     * Creates new form mn_pengajuan
     */
    
    File file;
    JFileChooser jfc;
    public mn_pengajuan() {
        initComponents();
        display_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slip = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        npwp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        periode = new javax.swing.JComboBox<>();
        terima = new javax.swing.JButton();
        simpan_image = new javax.swing.JButton();
        reset_image = new javax.swing.JButton();
        lblnmfile = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        icon_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        penghasilan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txttitle = new javax.swing.JComboBox<>();
        pilihfile1 = new javax.swing.JButton();
        lihat = new javax.swing.JButton();
        pilihfile2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        pilihfile3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        update_image = new javax.swing.JButton();
        pinjaman = new javax.swing.JComboBox<>();
        no_telp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ktp = new javax.swing.JTextField();
        angsuran = new javax.swing.JTextField();

        setTitle("Menu Pengajuan");

        slip.setEditable(false);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Lihat File");
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        jLabel14.setFocusable(false);
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        npwp.setEditable(false);

        jLabel8.setText("ID");

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        periode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "6 Bulan", "9 Bulan", "12 Bulan" }));
        periode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periodeActionPerformed(evt);
            }
        });

        terima.setText("Terima");
        terima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaActionPerformed(evt);
            }
        });

        simpan_image.setText("Simpan");
        simpan_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_imageActionPerformed(evt);
            }
        });

        reset_image.setText("Reset");
        reset_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_imageActionPerformed(evt);
            }
        });

        lblnmfile.setBackground(new java.awt.Color(240, 240, 240));
        lblnmfile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnmfile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblnmfile.setText("Nama File");
        lblnmfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblnmfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblnmfileActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        icon_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_image.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "NIK", "No. Telp", "Penghasilan", "Pinjaman", "Periode", "KTP", "Slip Gajih", "NPWPl"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("Periode");

        jLabel5.setText("KTP");

        penghasilan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kurang dari Rp. 500.000", "Rp. 500.000 - Rp. 1.000.000", "Rp. 1.000.000 - Rp. 2.000.000", "Rp. 2.000.000", "Rp. 5.000.000", "Lebih dari Rp. 5.000.000" }));
        penghasilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penghasilanActionPerformed(evt);
            }
        });

        jLabel6.setText("Slip Gajih");

        jLabel9.setText("Penghasilan");

        jLabel11.setText("NPWP");

        jLabel10.setText("Pinjaman");

        txttitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Kartu Tanda Penduduk", "Slip Gajih", "NPWP" }));

        pilihfile1.setText("Pilih File");
        pilihfile1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pilihfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihfile1ActionPerformed(evt);
            }
        });

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        pilihfile2.setText("Pilih File");
        pilihfile2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pilihfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihfile2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis");

        pilihfile3.setText("Pilih File");
        pilihfile3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pilihfile3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihfile3ActionPerformed(evt);
            }
        });

        jLabel7.setText("No. Telp");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Menu Pengajuan");

        jLabel2.setText("Nama");

        jLabel4.setText("NIK ");

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.setMaximumSize(new java.awt.Dimension(94, 29));
        tambah.setMinimumSize(new java.awt.Dimension(94, 29));
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        hapus.setText("Ditolak");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.setMaximumSize(new java.awt.Dimension(94, 29));
        ubah.setMinimumSize(new java.awt.Dimension(94, 29));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        update_image.setText("Perbarui");
        update_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_imageActionPerformed(evt);
            }
        });

        pinjaman.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Rp. 3.000.000", "Rp. 5.000.000", "Rp. 10.000.000" }));
        pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamanActionPerformed(evt);
            }
        });

        jLabel13.setText("Angsuran");

        ktp.setEditable(false);

        angsuran.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pilihfile2)
                            .addComponent(pilihfile1)
                            .addComponent(pilihfile3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(ktp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(slip, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(npwp)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_telp)
                            .addComponent(nik)
                            .addComponent(nama)
                            .addComponent(id)
                            .addComponent(penghasilan, 0, 258, Short.MAX_VALUE)
                            .addComponent(pinjaman, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(periode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(angsuran)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lihat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terima, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(update_image)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(reset_image, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpan_image, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblnmfile, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icon_image, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblnmfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(icon_image, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pilihfile1)
                                    .addComponent(ktp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pilihfile2)
                                    .addComponent(slip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pilihfile3)
                                    .addComponent(npwp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reset)))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lihat)
                            .addComponent(terima)
                            .addComponent(update_image)
                            .addComponent(reset_image)
                            .addComponent(simpan_image)
                            .addComponent(hapus))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void periodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periodeActionPerformed
        // TODO add your handling code here:
        String PINJAMAN = (String) pinjaman.getSelectedItem();
        String PERIODE = (String) periode.getSelectedItem();
        if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 500.000");
        }else if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 350.000");
        }else if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 300.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 1.700.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 850.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 450.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 3.500.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 1.500.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 850.000");
        }
    }//GEN-LAST:event_periodeActionPerformed

    private void terimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaActionPerformed
        // TODO add your handling code here:
        String ID=id.getText();
        String STATUS="Survey";

        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah !");
        }else{
            try {
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE tb_pengajuan SET status = '"+STATUS+"' WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Pengajuan Berkas Telah diterima");
                display_data(); //refresh table
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Pengjuan Berkas Gagal");
            }
        }
    }//GEN-LAST:event_terimaActionPerformed

    private void simpan_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_imageActionPerformed
        // TODO add your handling code here:
        String NAMA_IMAGE = lblnmfile.getText();
        String JUDUL = (String) txttitle.getSelectedItem();
        if (NAMA_IMAGE.equals("") || JUDUL.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Harap isi pilih file dan jenis file dengan benar!");
        }else {
            try {
                String path=new File(".").getCanonicalPath();
                FileUtils.copyFileToDirectory(file, new File(path+"/image"));
//                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
//                java.sql.PreparedStatement s = Vconn.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+ID+"','"+JUDUL+"','"+NAMA_IMAGE+"')");
//                s.execute();
                JOptionPane.showMessageDialog(null, "File Berhasil Disimpan");
                reset_image();
            } catch (IOException ex) {
                Logger.getLogger(SaveImage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_simpan_imageActionPerformed

    private void reset_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_imageActionPerformed
        // TODO add your handling code here:
        icon_image.setIcon(null);
        txttitle.setSelectedIndex(0);
        lblnmfile.setText("IMAGE");

    }//GEN-LAST:event_reset_imageActionPerformed

    private void lblnmfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblnmfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblnmfileActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String ID = jTable1.getValueAt(baris, 0).toString();
        id.setText(ID);
        String NAMA = jTable1.getValueAt(baris, 1).toString();
        nama.setText(NAMA);
        String NIK = jTable1.getValueAt(baris, 2).toString();
        nik.setText(NIK);
        String NO_TELP = jTable1.getValueAt(baris, 3).toString();
        no_telp.setText(NO_TELP);
        String PENGHASILAN = jTable1.getValueAt(baris, 4).toString();
        penghasilan.setSelectedItem(PENGHASILAN);
        String PINJAMAN = jTable1.getValueAt(baris, 5).toString();
        pinjaman.setSelectedItem(PINJAMAN);
        String PERIODE = jTable1.getValueAt(baris, 6).toString();
        periode.setSelectedItem(PERIODE);
        String ANGSURAN = jTable1.getValueAt(baris, 7).toString();
        angsuran.setText(ANGSURAN);
        String KTP = jTable1.getValueAt(baris, 8).toString();
        ktp.setText(KTP);
        String SLIP_GAJIH = jTable1.getValueAt(baris, 9).toString();
        slip.setText(SLIP_GAJIH);
        String NPWP = jTable1.getValueAt(baris, 10).toString();
        npwp.setText(NPWP);
    }//GEN-LAST:event_jTable1MouseClicked

    private void penghasilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penghasilanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penghasilanActionPerformed

    private void pilihfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihfile1ActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(icon_image)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(285, 300, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            icon_image.setIcon(imageIcon);
            lblnmfile.setText(jfc.getSelectedFile().getName());
            ktp.setText(jfc.getSelectedFile().getName());
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pilihfile1ActionPerformed

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            new SaveImage(ID).setVisible(true);
        }

    }//GEN-LAST:event_lihatActionPerformed

    private void pilihfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihfile2ActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(icon_image)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(285, 300, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            icon_image.setIcon(imageIcon);
            lblnmfile.setText(jfc.getSelectedFile().getName());
            slip.setText(jfc.getSelectedFile().getName());
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pilihfile2ActionPerformed

    private void pilihfile3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihfile3ActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(icon_image)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(285, 300, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            icon_image.setIcon(imageIcon);
            lblnmfile.setText(jfc.getSelectedFile().getName());
            npwp.setText(jfc.getSelectedFile().getName());
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pilihfile3ActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here
        String NAMA = nama.getText();
        String NIK = nik.getText();
        String NO_TELP = no_telp.getText();
        String PENGHASILAN = (String) penghasilan.getSelectedItem();
        String PINJAMAN = (String) pinjaman.getSelectedItem();
        String PERIODE = (String) periode.getSelectedItem();
        String ANGSURAN = angsuran.getText();
        String KTP = ktp.getText();
        String SLIP_GAJIH = slip.getText();
        String NPWP = npwp.getText();
        String RUMAH = "";
        String SURAT_PERNYATAAN = "";
        String TANGGAL = "";
        String STATUS="Pengajuan";

        if(NAMA.equals("")||NIK.equals("")||PINJAMAN.equals("") ||PERIODE.equals("")||NO_TELP.equals("")||PENGHASILAN.equals("")||PINJAMAN.equals("")||ANGSURAN.equals("")||KTP.equals("")||SLIP_GAJIH.equals("")||NPWP.equals("")){
            JOptionPane.showMessageDialog(null,"Harap isi formulir dengan benar dan lengkap !");
        }else{
            try {
                java.sql.Connection coba = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement coba_lagi = coba.prepareStatement("INSERT INTO tb_pengajuan (nama,nik,no_telp,penghasilan,pinjaman,periode,angsuran,ktp,slip_gajih,npwp,status,foto_rumah,surat_pernyataan,tanggal_pencairan) VALUES ('"+NAMA+"','"+NIK+"','"+NO_TELP+"','"+PENGHASILAN+"','"+PINJAMAN+"','"+PERIODE+"','"+ANGSURAN+"','"+KTP+"','"+SLIP_GAJIH+"','"+NPWP+"','"+STATUS+"','"+RUMAH+"','"+SURAT_PERNYATAAN+"','"+TANGGAL+"')");
                coba_lagi.execute();
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.Statement s = Vconn.createStatement();
                java.sql.ResultSet r = s.executeQuery("SELECT ID FROM tb_pengajuan ORDER BY ID DESC LIMIT 1");
                
                while (r.next()){
                    id.setText(r.getString("ID"));
                }
                
                String GetId = id.getText();
                String JUDUL1="Kartu Tanda Penduduk";
                String JUDUL2="Slip Gajih";
                String JUDUL3="NPWP";
//                String GetId = r.getString("ID");
                java.sql.Connection image = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement simpan_gambar = image.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+GetId+"','"+JUDUL1+"','"+KTP+"')");
                simpan_gambar.execute();
                
                java.sql.Connection image1 = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement simpan_gambar1 = image1.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+GetId+"','"+JUDUL2+"','"+SLIP_GAJIH+"')");
                simpan_gambar1.execute();
                
                java.sql.Connection image2 = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement simpan_gambar2 = image2.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+GetId+"','"+JUDUL3+"','"+NPWP+"')");
                simpan_gambar2.execute();
              
                JOptionPane.showMessageDialog(null,"Pengajuan telah ditambahkan");
            }catch (HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null,"Pengajuan gagal ditambahkan");
            }
            display_data();
            reset();
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            try{
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement(" DELETE FROM tb_pengajuan WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Delete data Nasabah berhasil");
                display_data();
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Delete data Nasabah gagal");
            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        String NAMA = nama.getText();
        String NIK = nik.getText();
        String NO_TELP = no_telp.getText();
        String PENGHASILAN = (String) penghasilan.getSelectedItem();
        String PINJAMAN = (String) pinjaman.getSelectedItem();
        String PERIODE = (String) periode.getSelectedItem();
        String ANGSURAN = angsuran.getText();
        String KTP = ktp.getText();
        String SLIP_GAJIH = slip.getText();
        String NPWP = npwp.getText();
        String STATUS="Pengajuan";

        if(NAMA.equals("")||NIK.equals("")||PINJAMAN.equals("") ||PERIODE.equals("")||NO_TELP.equals("")||PENGHASILAN.equals("")||KTP.equals("")||SLIP_GAJIH.equals("")||NPWP.equals("")){
            JOptionPane.showMessageDialog(null,"Harap isi formulir dengan benar dan lengkap !");
        }else{
            try {
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE tb_pengajuan SET nama = '"+NAMA+"', nik = '"+NIK+"', no_telp = '"+NO_TELP+"', penghasilan = '"+PENGHASILAN+"', pinjaman = '"+PINJAMAN+"', periode = '"+PERIODE+"', angsuran = '"+ANGSURAN+"',ktp = '"+KTP+"', slip_gajih = '"+SLIP_GAJIH+"', npwp = '"+NPWP+"', status = '"+STATUS+"' WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Edit data nasabah berhasil");
                display_data(); //refresh table
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Edit data nasabah gagal");
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void update_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_imageActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        String NAMA_IMAGE = lblnmfile.getText();
        String JUDUL = (String) txttitle.getSelectedItem();
        if (ID.equals("") || NAMA_IMAGE.equals("") || JUDUL.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Harap isi pilih file dan jenis file dengan benar!");
        }else {
            try {
                String path=new File(".").getCanonicalPath();
                FileUtils.copyFileToDirectory(file, new File(path+"/image"));

                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE gambar SET image = '"+NAMA_IMAGE+"', title = '"+JUDUL+"' WHERE ID = '"+ID+"' AND title = '"+JUDUL+"' ");
                pst.execute();
                JOptionPane.showMessageDialog(null, "File Berhasil diupdate");
                reset_image();
            } catch (IOException ex) {
                Logger.getLogger(SaveImage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex ) {
                Logger.getLogger(mn_pengajuan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_update_imageActionPerformed

    private void pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamanActionPerformed
        // TODO add your handling code here:
        String PINJAMAN = (String) pinjaman.getSelectedItem();
        String PERIODE = (String) periode.getSelectedItem();
        if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 500.000");
        }else if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 350.000");
        }else if (PINJAMAN.equals("Rp. 3.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 300.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 1.700.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 850.000");
        }else if (PINJAMAN.equals("Rp. 5.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 450.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("6 Bulan")){
            angsuran.setText("Rp. 3.500.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("9 Bulan")){
            angsuran.setText("Rp. 1.500.000");
        }else if (PINJAMAN.equals("Rp. 10.000.000") && PERIODE.equals("12 Bulan")){
            angsuran.setText("Rp. 850.000");
        }
    }//GEN-LAST:event_pinjamanActionPerformed

    private void reset (){
        id.setText("");
        nama.setText("");
        nik.setText("");
        no_telp.setText("");
        penghasilan.setSelectedIndex(0);
        periode.setSelectedIndex(0);
        pinjaman.setSelectedIndex(0);
        angsuran.setText("");
        ktp.setText("");
        slip.setText("");
        npwp.setText("");  
    }
    
    private void reset_image (){
        icon_image.setIcon(null);
        txttitle.setSelectedIndex(0);
        lblnmfile.setText("IMAGE");  
    }
    
    private void display_data()
    {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("NIK");
        tabel.addColumn("No. Telp");
        tabel.addColumn("Penghasilan");
        tabel.addColumn("Pinjaman");
        tabel.addColumn("Periode");
        tabel.addColumn("Angsuran");
        tabel.addColumn("KTP");
        tabel.addColumn("Slip Gajih");
        tabel.addColumn("NPWP");
        String STATUS = "Pengajuan";
        
        try{
            java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
            java.sql.Statement s = Vconn.createStatement();
            java.sql.ResultSet r = s.executeQuery("SELECT * FROM tb_pengajuan WHERE status = '"+STATUS+"' ");
//            SELECT id_user FROM tb_user ORDER BY id_user DESC LIMIT 1
            
            //menampilkan data
            while (r.next()){
                tabel.addRow(new Object[]{
                   r.getString(1),r.getString(2),r.getString(3), r.getString(4), r.getString(5),r.getString(6),r.getString(7), r.getString(8), r.getString(9),r.getString(10),r.getString(11)
                }); 
            }
            jTable1.setModel(tabel);
            
            
        }catch (SQLException e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angsuran;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel icon_image;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ktp;
    private javax.swing.JTextField lblnmfile;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField npwp;
    private javax.swing.JComboBox<String> penghasilan;
    private javax.swing.JComboBox<String> periode;
    private javax.swing.JButton pilihfile1;
    private javax.swing.JButton pilihfile2;
    private javax.swing.JButton pilihfile3;
    private javax.swing.JComboBox<String> pinjaman;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_image;
    private javax.swing.JButton simpan_image;
    private javax.swing.JTextField slip;
    private javax.swing.JButton tambah;
    private javax.swing.JButton terima;
    private javax.swing.JComboBox<String> txttitle;
    private javax.swing.JButton ubah;
    private javax.swing.JButton update_image;
    // End of variables declaration//GEN-END:variables
}
