/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;


import Gui.SaveImage;
import com.mysql.jdbc.jdbc2.optional.MysqlDataSource;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

import org.apache.commons.io.FileUtils;
/**
 *
 * @author ACER
 */
public class mn_survey extends javax.swing.JFrame {

    /**
     * Creates new form mn_survey
     */

    File file;
    JFileChooser jfc;
    public mn_survey() {
        initComponents();
        display_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reset_image = new javax.swing.JButton();
        lblnmfile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        icon_image = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ubah = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        txttitle = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lihat = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        update_image = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pinjaman = new javax.swing.JTextField();
        pilihfile1 = new javax.swing.JButton();
        pilihfile2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        no_telp = new javax.swing.JTextField();
        foto_rumah = new javax.swing.JTextField();
        surat_pernyataan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        terima = new javax.swing.JButton();
        simpan_image = new javax.swing.JButton();
        periode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        penghasilan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        angsuran = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setTitle("Menu Survey");

        reset_image.setText("Reset");
        reset_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_imageActionPerformed(evt);
            }
        });

        lblnmfile.setBackground(new java.awt.Color(240, 240, 240));
        lblnmfile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblnmfile.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblnmfile.setText("IMAGE");
        lblnmfile.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("NIK ");

        icon_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_image.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nama.setEditable(false);
        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });

        jLabel3.setText("Periode");

        nik.setEditable(false);

        jLabel5.setText("Rumah");

        ubah.setText("Perbarui");
        ubah.setMaximumSize(new java.awt.Dimension(94, 29));
        ubah.setMinimumSize(new java.awt.Dimension(94, 29));
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        jLabel6.setText("Surat Pernyataan");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        txttitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Rumah", "Surat Pernyataan" }));

        jTable1.setBackground(new java.awt.Color(240, 240, 240));
        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "NIK", "No. Telp", "Penghasilan", "Pinjaman", "Periode", "KTP", "Slip Gajih", "NPWPl"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lihat.setText("Lihat");
        lihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis");

        jLabel9.setText("Penghasilan");

        update_image.setText("Perbarui");
        update_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_imageActionPerformed(evt);
            }
        });

        jLabel10.setText("Pinjaman");

        pinjaman.setEditable(false);
        pinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinjamanActionPerformed(evt);
            }
        });

        pilihfile1.setText("Pilih File");
        pilihfile1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pilihfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihfile1ActionPerformed(evt);
            }
        });

        pilihfile2.setText("Pilih File");
        pilihfile2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pilihfile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihfile2ActionPerformed(evt);
            }
        });

        jLabel7.setText("No. Telp");

        no_telp.setEditable(false);

        foto_rumah.setEditable(false);

        surat_pernyataan.setEditable(false);

        jLabel8.setText("ID");

        id.setEditable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        terima.setText("Terima");
        terima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaActionPerformed(evt);
            }
        });

        simpan_image.setText("Simpan");
        simpan_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_imageActionPerformed(evt);
            }
        });

        periode.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Menu Survey");

        penghasilan.setEditable(false);

        jLabel2.setText("Nama");

        jLabel11.setText("Angsuran");

        angsuran.setEditable(false);

        jButton1.setText("Ditolak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pilihfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(pilihfile2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(foto_rumah, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(surat_pernyataan)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(periode)
                                    .addComponent(no_telp)
                                    .addComponent(nik)
                                    .addComponent(nama)
                                    .addComponent(id)
                                    .addComponent(pinjaman)
                                    .addComponent(penghasilan)
                                    .addComponent(angsuran))))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lihat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(terima, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(update_image)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(reset_image, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(simpan_image, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblnmfile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txttitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(icon_image, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblnmfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(icon_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(pinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(periode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilihfile1)
                            .addComponent(foto_rumah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pilihfile2)
                            .addComponent(surat_pernyataan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(reset)
                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lihat))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simpan_image)
                        .addComponent(reset_image)
                        .addComponent(terima)
                        .addComponent(update_image)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_imageActionPerformed
        // TODO add your handling code here:
        icon_image.setIcon(null);
        txttitle.setSelectedIndex(0);
        lblnmfile.setText("IMAGE");

    }//GEN-LAST:event_reset_imageActionPerformed

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        String NAMA = nama.getText();
        String NIK = nik.getText();
        String NO_TELP = no_telp.getText();
        String PENGHASILAN = penghasilan.getText();
        String PINJAMAN = pinjaman.getText();
        String PERIODE = periode.getText();
        String ANGSURAN = angsuran.getText();
        String RUMAH = foto_rumah.getText();
        String SP = surat_pernyataan.getText();
        String STATUS="Survey";

        if(NAMA.equals("")||NIK.equals("")||PINJAMAN.equals("") ||PERIODE.equals("")||NO_TELP.equals("")||PENGHASILAN.equals("")||RUMAH.equals("")||SP.equals("")){
            JOptionPane.showMessageDialog(null,"Harap isi formulir dengan benar dan lengkap !");
        }else{
            try {
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE tb_pengajuan SET nama = '"+NAMA+"', nik = '"+NIK+"', no_telp = '"+NO_TELP+"', penghasilan = '"+PENGHASILAN+"', pinjaman = '"+PINJAMAN+"', periode = '"+PERIODE+"', angsuran = '"+ANGSURAN+"', foto_rumah = '"+RUMAH+"', surat_pernyataan = '"+SP+"',  status = '"+STATUS+"' WHERE ID = '"+ID+"'");
                pst.execute();
                
                String JUDUL1="Foto Rumah";
                String JUDUL2="Surat Pernyataan";
//              String GetId = r.getString("ID");
                java.sql.Connection image = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement simpan_gambar = image.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+ID+"','"+JUDUL1+"','"+RUMAH+"')");
                simpan_gambar.execute();
                
                java.sql.Connection image1 = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement simpan_gambar1 = image1.prepareStatement("INSERT INTO gambar (ID,title,image) VALUES ('"+ID+"','"+JUDUL2+"','"+SP+"')");
                simpan_gambar1.execute();
                
                JOptionPane.showMessageDialog(null, "Berkas berhasil dilengkapi");
                display_data(); //refresh table
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Berkas gagal dilengkapi");
            }
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_resetActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String ID = jTable1.getValueAt(baris, 0).toString();
        id.setText(ID);
        String NAMA = jTable1.getValueAt(baris, 1).toString();
        nama.setText(NAMA);
        String NIK = jTable1.getValueAt(baris, 2).toString();
        nik.setText(NIK);
        String NO_TELP = jTable1.getValueAt(baris, 3).toString();
        no_telp.setText(NO_TELP);
        String PENGHASILAN = jTable1.getValueAt(baris, 4).toString();
        penghasilan.setText(PENGHASILAN);
        String PINJAMAN = jTable1.getValueAt(baris, 5).toString();
        pinjaman.setText(PINJAMAN);
        String PERIODE = jTable1.getValueAt(baris, 6).toString();
        periode.setText(PERIODE);
        String ANGSURAN = jTable1.getValueAt(baris, 7).toString();
        angsuran.setText(ANGSURAN);
        String rumah = jTable1.getValueAt(baris, 8).toString();
        foto_rumah.setText(rumah);
        String SP = jTable1.getValueAt(baris, 9).toString();
        surat_pernyataan.setText(SP);

    }//GEN-LAST:event_jTable1MouseClicked

    private void lihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            new SaveImage(ID).setVisible(true);
        }

    }//GEN-LAST:event_lihatActionPerformed

    private void update_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_imageActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        String NAMA_IMAGE = lblnmfile.getText();
        String JUDUL = (String) txttitle.getSelectedItem();
        if (ID.equals("") || NAMA_IMAGE.equals("") || JUDUL.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Harap isi pilih file dan jenis file dengan benar!");
        }else {
            try {
                String path=new File(".").getCanonicalPath();
                FileUtils.copyFileToDirectory(file, new File(path+"/image"));

                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE gambar SET image = '"+NAMA_IMAGE+"', title = '"+JUDUL+"' WHERE ID = '"+ID+"' AND title = '"+JUDUL+"' ");
                pst.execute();
                JOptionPane.showMessageDialog(null, "File Berhasil diupdate");
                reset_image();
            } catch (IOException ex) {
                Logger.getLogger(SaveImage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex ) {
                Logger.getLogger(mn_survey.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_update_imageActionPerformed

    private void pinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinjamanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinjamanActionPerformed

    private void pilihfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihfile1ActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(icon_image)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(285, 300, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            icon_image.setIcon(imageIcon);
            lblnmfile.setText(jfc.getSelectedFile().getName());
            foto_rumah.setText(jfc.getSelectedFile().getName());
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pilihfile1ActionPerformed

    private void pilihfile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihfile2ActionPerformed
        // TODO add your handling code here:
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(icon_image)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(285, 300, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            icon_image.setIcon(imageIcon);
            lblnmfile.setText(jfc.getSelectedFile().getName());
            surat_pernyataan.setText(jfc.getSelectedFile().getName());
            file=new File(jfc.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_pilihfile2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void terimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaActionPerformed
        // TODO add your handling code here:
        String ID=id.getText();
        String STATUS="Audit";

        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah !");
        }else{
            try {
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement("UPDATE tb_pengajuan SET status = '"+STATUS+"' WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nasabah telah disurvey");
                display_data(); //refresh table
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Nasabah telah tidak lulus survey");
            }
        }
    }//GEN-LAST:event_terimaActionPerformed

    private void simpan_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_imageActionPerformed
        // TODO add your handling code here:
        String NAMA_IMAGE = lblnmfile.getText();
        String JUDUL = (String) txttitle.getSelectedItem();
        if (NAMA_IMAGE.equals("") || JUDUL.equals("Pilih")){
            JOptionPane.showMessageDialog(null, "Harap isi pilih file dan jenis file dengan benar!");
        }else {
            try {
                String path=new File(".").getCanonicalPath();
                FileUtils.copyFileToDirectory(file, new File(path+"/image"));
                
                JOptionPane.showMessageDialog(null, "File Berhasil Disimpan");
                reset_image();
            } catch (IOException ex) {
                Logger.getLogger(SaveImage.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }
    }//GEN-LAST:event_simpan_imageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String ID = id.getText();
        if(ID.equals("")){
            JOptionPane.showMessageDialog(null,"Pilih Nasabah");
        }else{
            try{
                java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
                java.sql.PreparedStatement pst = Vconn.prepareStatement(" DELETE FROM tb_pengajuan WHERE ID = '"+ID+"'");
                pst.execute();
                JOptionPane.showMessageDialog(null, "Nasabah Ditolak");
                display_data();
                reset();
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "Nasabah gagal ditoak");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

private void reset (){
        id.setText("");
        nama.setText("");
        nik.setText("");
        no_telp.setText("");
        penghasilan.setText("");
        periode.setText("");
        pinjaman.setText("");
        angsuran.setText("");
        foto_rumah.setText("");
        surat_pernyataan.setText("");
    }
    
    private void reset_image (){
        icon_image.setIcon(null);
        txttitle.setSelectedIndex(0);
        lblnmfile.setText("IMAGE");  
    }
    
    private void display_data()
    {
        DefaultTableModel tabel = new DefaultTableModel();
        tabel.addColumn("ID");
        tabel.addColumn("Nama");
        tabel.addColumn("NIK");
        tabel.addColumn("No. Telp");
        tabel.addColumn("Penghasilan");
        tabel.addColumn("Pinjaman");
        tabel.addColumn("Periode");
        tabel.addColumn("Angsuran");
        tabel.addColumn("Rumah");
        tabel.addColumn("SP");
        String STATUS = "Survey";
        
        try{
            java.sql.Connection Vconn = (Connection)koneksiDB.configDB();
            java.sql.Statement s = Vconn.createStatement();
            java.sql.ResultSet r = s.executeQuery("SELECT * FROM tb_pengajuan WHERE status = '"+STATUS+"' ");
//            SELECT id_user FROM tb_user ORDER BY id_user DESC LIMIT 1
            
            //menampilkan data
            while (r.next()){
                tabel.addRow(new Object[]{
                   r.getString(1),r.getString(2),r.getString(3), r.getString(4), r.getString(5),r.getString(6),r.getString(7), r.getString(8),r.getString(13), r.getString(14)
                }); 
            }
            jTable1.setModel(tabel);
            
            
        }catch (SQLException e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angsuran;
    private javax.swing.JTextField foto_rumah;
    private javax.swing.JLabel icon_image;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblnmfile;
    private javax.swing.JButton lihat;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTextField penghasilan;
    private javax.swing.JTextField periode;
    private javax.swing.JButton pilihfile1;
    private javax.swing.JButton pilihfile2;
    private javax.swing.JTextField pinjaman;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset_image;
    private javax.swing.JButton simpan_image;
    private javax.swing.JTextField surat_pernyataan;
    private javax.swing.JButton terima;
    private javax.swing.JComboBox<String> txttitle;
    private javax.swing.JButton ubah;
    private javax.swing.JButton update_image;
    // End of variables declaration//GEN-END:variables
}
